Update README
thepinetree/plaid-templates pull request #6
Opened 2020-09-15 15:55 UTC by shiftsayan

2020-09-15 16:02 UTC, thepinetree commented
Add README in homework directory and good to go

2020-09-16 00:17 UTC, thepinetree requested changes
Add README in homework directory and good to go!

2020-09-16 18:49 UTC, thepinetree requested changes

2020-09-16 18:49 UTC, thepinetree commented on homework/README.md
> +pdflatex hw.tex
add a dollar sign here real quick and make this the sentence
Compiler your document locally (shown below) or upload it to Overleaf

2020-09-16 18:49 UTC, thepinetree commented on homework/README.md
> +1. Edit the `Settings` section in `hw.tex` with your personal and class information
I don't think this is clear since there's no Settings demarcation, changing to
Edit the settings in the `hw.tex` preamble with your personal and class information
OR
updating hw.tex to have a `Settings` is best here.

2020-09-16 18:51 UTC, thepinetree commented on README.md
> +This repository features a useful set of templates for Carnegie Mellon University students.
actually can we change this from Carnegie Mellon University to Carnegie Mellon University students (and all other LaTeX users)!

2020-09-16 18:52 UTC, shiftsayan commented on homework/README.md
> +pdflatex hw.tex
Added $ and reworded it in the new commit

2020-09-16 18:53 UTC, shiftsayan commented on homework/README.md
> +1. Edit the `Settings` section in `hw.tex` with your personal and class information
Yep, will update hw.tex in the other PR (slightly undesirable, but don't want to run into merge conflicts)

Actually. hw.tex doesn't exist right now but will set that up in another PR

2020-09-16 18:54 UTC, shiftsayan commented on README.md
> +This repository features a useful set of templates for Carnegie Mellon University students.
Hmmm, is this LaTeX specific?

2020-09-16 18:55 UTC, thepinetree commented on README.md
> +This repository features a useful set of templates for Carnegie Mellon University students.
right, all other university students?

2020-09-16 18:59 UTC, merged