Update template
thepinetree/plaid-templates pull request #7
Opened 2020-09-15 17:51 UTC by shiftsayan

2020-09-16 00:33 UTC, thepinetree requested changes
Some minor nits and design decisions. Main thing is getting in induction template here so doc compiles.

2020-09-16 00:33 UTC, thepinetree commented on homework/hw_example.tex
> +\begin{document}
Remove unnecessary space

2020-09-16 00:33 UTC, thepinetree commented on homework/plaid-homework.cls
> +%* Classes                                                                    *%
Hmm I kinda like the centering, have been using this:
`echo "text" | boxes -a hcvc -s 80x3` to do it

2020-09-16 00:33 UTC, thepinetree commented on homework/hw_example.tex
> +\ul{hello}
This doesn't build right now with ul

2020-09-16 00:33 UTC, thepinetree commented on homework/plaid-homework.cls
> +% For better, more beautiful code support (including syntax coloring!)
Newline before this comment for separation

2020-09-16 00:33 UTC, thepinetree commented on homework/plaid-homework.cls
> +% For horizontally centering the \not command
I think these go better with the math stuff above for separation of intent

2020-09-16 00:33 UTC, thepinetree commented on homework/plaid-homework.cls
> +\graphicspath{{assets/}}
Describe what this is in a comment

2020-09-16 00:33 UTC, thepinetree commented on homework/plaid-homework.cls
> +% For conditionals
Should mention this is for LaTeX imo to differentiate from code listings

2020-09-16 00:33 UTC, thepinetree commented on homework/plaid-homework.cls
> +% SML Programming Declaration
This has to come before the lstset if the language in the above command is changed to sml

2020-09-16 00:33 UTC, thepinetree commented on homework/plaid-homework.cls
> +\newcommand{\RHS}{\underline{\textsf{RHS:}}}
Not a huge fan of the sf font, but not too attached to this either

2020-09-16 00:33 UTC, thepinetree commented on homework/plaid-homework.cls
> +% Usage: A \distas{distribution} B
This should be in probability, not calculus

2020-09-16 19:58 UTC, shiftsayan commented on homework/plaid-homework.cls
> +% SML Programming Declaration
ah I didn't know that!

2020-09-16 20:26 UTC, shiftsayan commented on homework/plaid-homework.cls
> +\newcommand{\RHS}{\underline{\textsf{RHS:}}}
Changed it to regular text. I am not a fan of texttt either, but I think just underline works.

2020-09-17 04:16 UTC, thepinetree requested changes
Just the spaces, then merge it.

2020-09-17 04:16 UTC, thepinetree commented on homework/hw-example.tex
> +\LaTeX is awesome for math! Let's look evaluating the value of $m$ if $(m + 2) \times (3 + 4) = 21$ in two ways.
This needs a space after \LaTeX. Should be \LaTeX\ is

2020-09-17 04:16 UTC, thepinetree commented on homework/hw-example.tex
> +You can code in \LaTeX too! Here's an intro to typesetting programs:
Same as above

2020-09-17 04:16 UTC, thepinetree commented on homework/hw-example.tex
> +Plotting in \LaTeX is super fun! Here's a mini graph with some shading:
Same as above

2020-09-17 04:38 UTC, thepinetree approved these changes

2020-09-17 04:39 UTC, merged